---
title: "527 project"
output: html_document
---

import data & data cleansing
```{r}
# healthcare project data
# train data
library(readr)
train_data <- read_csv("~/Downloads/healthcare/train_data.csv",show_col_types = FALSE)
#View(train_data)
na.omit(train_data)

#train_data$Hospital_code
train_data$Hospital_type_code=as.factor(train_data$Hospital_type_code)
train_data$Hospital_type_code=as.numeric(train_data$Hospital_type_code)
#train_data$City_Code_Hospital
train_data$Hospital_region_code=as.factor(train_data$Hospital_region_code)
train_data$Hospital_region_code=as.numeric(train_data$Hospital_region_code)
train_data$Department=as.factor(train_data$Department)
train_data$Department=as.numeric(train_data$Department)
train_data$Ward_Type=as.factor(train_data$Ward_Type)
train_data$Ward_Type=as.numeric(train_data$Ward_Type)
train_data$Ward_Facility_Code=as.factor(train_data$Ward_Facility_Code)
train_data$Ward_Facility_Code=as.numeric(train_data$Ward_Facility_Code)
train_data$`Bed Grade`=as.factor(train_data$`Bed Grade`)
train_data$`Bed Grade`=as.numeric(train_data$`Bed Grade`)
#train_data$City_Code_Patient

train_data$`Severity of Illness`=as.factor(train_data$`Severity of Illness`)
train_data$`Severity of Illness`=as.numeric(train_data$`Severity of Illness`)  # extreme=1, moderate=3, minor=2
train_data$Age=as.factor(train_data$Age)  
train_data$Age=as.numeric(train_data$Age)  # 6 as 50-60, etc
train_data$`Type of Admission`=as.factor(train_data$`Type of Admission`)
train_data$`Type of Admission`=as.numeric(train_data$`Type of Admission`)  # emergency=1, trauma=2, urgent=3
train_data$Stay=as.factor(train_data$Stay) 
train_data$Stay=as.numeric(train_data$Stay) # 0-10=1, 41-50=5, 31-40=4, 20-nov=2, 51-60=6, 71-80=8, more than 100=11, 81-90=9, 91-100=10, 61-70=7, 21-30=3

cor(train_data)

train_data=train_data[,-c(1,2,3,4,5,7,8,9,10,11,12)]  # delete unimportant variables



# define stay time over 70 days as long-term, others as short-term
long=train_data$Stay[train_data$Stay>6] # 2
short=train_data$Stay[train_data$Stay<=6] # 1
y2=as.integer(train_data$Stay<=6)
train_data=data.frame(train_data,y2)

# divide data into 70% training set and 30% test set
set.seed(1234)
train=sample(1:nrow(train_data), nrow(train_data)*0.7, FALSE)
data_train=train_data[train,]
data_test=train_data[-train,]

# test data for real prediction
test_data <- read_csv("~/Downloads/healthcare/test_data.csv",show_col_types = FALSE)
#View(test_data)
na.omit(test_data)

```


##### descriptive analysis

visualization
```{r}
# histogram for individual parameters of overall data set 
par(mfrow=c(2,3))
hist(train_data$Available.Extra.Rooms.in.Hospital, main ='Available Extra Rooms in Hospital')
hist(train_data$Type.of.Admission, main = 'Type of Admission')
hist(train_data$Severity.of.Illness, main = 'Severity of Illness')
hist(train_data$Visitors.with.Patient, main = 'Visitors with Patient')
hist(train_data$Age, main = 'Age')
hist(train_data$Admission_Deposit, main = 'Admission_Deposit')
par(mfrow=c(2,3))
hist(train_data$Stay, main = 'Stay')  # response
hist(long, main='long-term stay')
hist(short, main = 'short-term stay')

sum(long)
sum(short)

# correlation
cor(train_data)

```


##### predictive analytics

linear regression
```{r}
fit1=lm(y2~.-Stay, data = data_train)
summary(fit1)

```
All parameters are significant due to the p-value, but R-square is low, which this is not a good model for explaining Stay. 

outlier detection
```{r}
# we are dealing with categorical data
library(OutlierDetection)
X=train_data[1:1000,1:4]
OutlierDetection(X)  # not applicable to the categorical data
```



logistic regression
```{r}
glm.fit = glm(y2~.-Stay, data=data_train, family=binomial)
summary(glm.fit)

glm.probs = predict(glm.fit, data_test, type="response")
glm.pred = rep(0, length(glm.probs))
glm.pred[glm.probs>0.5] = 1
cm=table(glm.pred, data_test$y2) # confusion matrix
cm

# Test accuracy rate
sum(diag(cm))/sum(cm)   # 0.9243918

# Test error rate (Classification Error)
1-sum(diag(cm))/sum(cm)

```


decision tree (still working on)
```{r, warning=FALSE}
library(tree)
library(maptree)
tree.fit = tree(as.factor(y2)~as.factor(Severity.of.Illness)+as.factor(Age)+as.factor(Type.of.Admission)+Available.Extra.Rooms.in.Hospital+Visitors.with.Patient+Admission_Deposit, data = data_train)
summary(tree.fit)

# plot the tree    
draw.tree(tree.fit, nodeinfo=TRUE) 
title("Classification Tree Built on Training Set")

# Predict on test set
tree.pred = predict(tree.fit, data_test, type="class") 
#tree.pred


# Obtain confusion matrix
cm = table(tree.pred, data_test$y2)
cm

# Test accuracy rate
sum(diag(cm))/sum(cm)  # 0.9223716

# Test error rate (Classification Error)
1-sum(diag(cm))/sum(cm)

```



KNN
```{r}
library(tidyverse)
XTrain = data_train %>% select(-c(Stay,y2)) %>% scale(center = TRUE, scale = TRUE)
YTrain = data_train$y2
YTest = data_test$y2
XTest = data_test %>% select(-c(Stay,y2)) %>% scale(center = TRUE, scale = TRUE)
library(class)
set.seed(1234)
# KNN - train the classifier and make predictions on the training set
pred.YTtrain = knn(train=XTrain, test=XTrain, cl=YTrain, k=2)  # time-consuming
# Get confusion matrix
cm = table(predicted=pred.YTtrain, true=YTrain)
cm
# Test accuracy rate
sum(diag(cm)/sum(cm))   # 0.9408719
# Test error rate
1 - sum(diag(cm)/sum(cm))

```










